### ISSUE TITLE
wiki something wrong

### ISSUE THREAD

**Issue by hy2014** [wingify/lua-resty-rabbitmqstomp#1]
i can find redis in our readMe, i think it should be rabbitmq

**Comment by hy2014** [comment]
@bhaisaab

i found the message always add two EOF after the message, why we require it, does it will cause some issue if i remove these code?

**Comment by vaidik** [comment]
@hy2014 Yeah that should be rabbitmq.

**Comment by hy2014** [comment]
@bhaisaab 

sorry, i do now know your means, could you explain it more detail, thanks.

**Comment by vaidik** [comment]
In README, it should be rabbitmq and not redis.

**Comment by yadvr** [comment]
Fixed.
